import { useEffect, useMemo, useState, type CSSProperties } from 'react';
import { AppWindow, ChevronLeft, Gamepad2, Layers3, Search, X, type LucideIcon } from 'lucide-react';
import { seedApps } from './data/apps';
import { appStoreIcons, appStoreMetadata, appStoreScreenshots } from './data/appStoreIcons';
import { StoreApp } from './types';

type Tab = 'today' | 'apps' | 'games' | 'search';
type InstallStatus = 'idle' | 'loading' | 'paused' | 'open';
type InstallEntry = { status: InstallStatus; remaining: number; duration: number };
type Review = { name: string; title: string; body: string; stars: number; date: string };
const tabs: { id: Tab; label: string; icon: LucideIcon }[] = [{ id: 'today', label: 'Сегодня', icon: Layers3 }, { id: 'apps', label: 'Приложения', icon: AppWindow }, { id: 'games', label: 'Игры', icon: Gamepad2 }, { id: 'search', label: 'Поиск', icon: Search }];
const initialInstall: InstallEntry = { status: 'idle', remaining: 0, duration: 0 };
const reviewNames = ['Артём Лис', 'Мила Север', 'Кирилл Н.', 'Sasha Flow', 'Вика Миронова', 'Даня Котов', 'Roman Day', 'Лера Сокол', 'Максим Орлов', 'Ника Space'];
const reviewTitles = ['Отличное приложение', 'Пользуюсь каждый день', 'Очень удобно', 'Стало намного лучше', 'Приятный интерфейс', 'Работает стабильно', 'Советую попробовать', 'Хорошее обновление'];
const reviewBodies = ['Быстро открывается, всё понятно и без лишних действий. Пользоваться приятно.', 'После последних обновлений стало заметно удобнее. Дизайн аккуратный, функции на месте.', 'Нравится, что всё работает стабильно и не приходится долго разбираться.', 'Очень выручает каждый день. Интерфейс понятный, скорость хорошая.', 'Поставил бы 5 звёзд, но всегда есть куда расти. В целом впечатления отличные.', 'Красиво, быстро и удобно. Видно, что приложение делают с вниманием к деталям.', 'Редко пишу отзывы, но тут реально понравилось. Всё нужное под рукой.', 'Хорошее приложение, установил и оставил. Работает именно так, как ожидаешь.'];
function matchesApp(app: StoreApp, search: string) { const value = search.trim().toLowerCase(); return !value || [app.name, app.developer, app.category, app.subtitle, app.description, ...app.tags].join(' ').toLowerCase().includes(value); }
function hashId(id: string) { return id.split('').reduce((sum, char) => sum + char.charCodeAt(0), 0); }
function downloadDurationFor(appId: string) { const duration = 35 + ((hashId(appId) * 37) % 84); return duration === 60 || duration === 120 ? duration - 1 : duration; }
function formatDownloadTime(seconds: number) { if (seconds > 60) return `${Math.floor(seconds / 60)} мин. ${seconds % 60} сек.`; return `${seconds} сек.`; }
function getProgress(entry: InstallEntry) { const duration = entry.duration || 1; return Math.min(100, Math.max(0, ((duration - entry.remaining) / duration) * 100)); }
function stars(count: number) { return '★★★★★'.slice(0, count) + '☆☆☆☆☆'.slice(0, 5 - count); }
function reviewsFor(app: StoreApp): Review[] { const base = hashId(app.id); return [0, 1, 2].map((offset) => ({ name: reviewNames[(base + offset * 3) % reviewNames.length], title: reviewTitles[(base + offset * 2) % reviewTitles.length], body: reviewBodies[(base + offset * 5) % reviewBodies.length], stars: ((base + offset) % 3 === 0 ? 4 : 5), date: [`${2 + offset} дн. назад`, `${1 + offset} нед. назад`, `${2 + offset} мес. назад`][offset] })); }
function AppIcon({ app, large = false }: { app: StoreApp; large?: boolean }) { const iconUrl = appStoreIcons[app.id]; return <div className={`app-icon ${large ? 'large' : ''}`} style={{ background: app.iconGradient }}><span className="icon-fallback">{app.iconText}</span>{iconUrl && <img className="app-icon-art" src={iconUrl} alt="" loading="lazy" />}<span className="icon-shine" /></div>; }
function ShareGlyph() { return <span className="ios-share-glyph"><i /><b /></span>; }
function DownloadStatus({ entry, onToggle }: { entry: InstallEntry; onToggle: () => void }) { const paused = entry.status === 'paused'; const progress = getProgress(entry); return <div className="download-status"><button className={`download-status-icon ${paused ? 'paused' : 'loading'}`} style={{ '--progress': `${progress}%` } as Record<string, string>} onClick={onToggle} aria-label={paused ? 'Продолжить установку' : 'Остановить установку'}>{paused ? <span className="resume-triangle" /> : <span className="download-status-bars"><i /><i /></span>}</button><span>{paused ? 'Приостановлено' : formatDownloadTime(entry.remaining)}</span></div>; }
function ActionButton({ entry, onToggle, variant = 'compact' }: { entry: InstallEntry; onToggle: () => void; variant?: 'compact' | 'detail' }) { if (variant === 'detail' && (entry.status === 'loading' || entry.status === 'paused')) return <DownloadStatus entry={entry} onToggle={onToggle} />; const label = entry.status === 'open' ? 'Открыть' : entry.status === 'loading' ? formatDownloadTime(entry.remaining) : entry.status === 'paused' ? '▶' : 'Скачать'; return <button className={`action-pill ${entry.status}`} onClick={onToggle}>{entry.status === 'loading' && <span className="loader" />}<span>{label}</span></button>; }
function AppScreens({ app }: { app: StoreApp }) { const shots = appStoreScreenshots[app.id] ?? []; return <div className="screenshot-strip">{shots.length ? shots.map((shot, index) => <img key={shot} className="real-shot" src={shot} alt={`${app.name} скриншот ${index + 1}`} loading="lazy" />) : app.screenshots.map((screen, index) => <div key={screen} className="fake-shot" style={{ background: app.iconGradient }}><span>{screen}</span><small>{index + 1}</small></div>)}</div>; }
function MetaStrip({ app }: { app: StoreApp }) { const meta = appStoreMetadata[app.id] ?? {}; const rating = meta.rating || app.rating; const count = meta.ratingsCount || app.reviews; const age = meta.ageRating || '12+'; const category = meta.category || app.category; const developer = meta.developer || app.developer; const lang = meta.languages || 'RU'; const more = meta.languagesMore ? `+ ${meta.languagesMore} ещё` : 'язык'; const size = meta.size || '—'; const version = meta.version || '—'; const items = [{ label: `${count} оценок`, value: rating, sub: '★ ★ ★ ★ ☆' }, { label: 'Возраст', value: age, sub: 'рейтинг' }, { label: 'Категория', value: category, sub: app.rank || 'чарт' }, { label: 'Разработчик', value: '👤', sub: developer }, { label: 'Язык', value: lang, sub: more }, { label: 'Размер', value: size, sub: 'приложение' }, { label: 'Версия', value: version, sub: 'текущая' }]; return <div className="meta-strip appstore-meta-strip">{items.map((item) => <div key={item.label} className="meta-card"><span className="meta-label">{item.label}</span><strong>{item.value}</strong><span className="meta-sub">{item.sub}</span></div>)}</div>; }
function Reviews({ app }: { app: StoreApp }) { const meta = appStoreMetadata[app.id] ?? {}; const rating = meta.rating || app.rating; const count = meta.ratingsCount || app.reviews; const list = reviewsFor(app); return <section className="reviews-section"><div className="reviews-head"><h2>Оценки и отзывы</h2><button>Все</button></div><div className="rating-summary"><div><strong>{rating}</strong><span>из 5</span></div><div><p className="big-stars">★★★★★</p><small>{count} оценок</small></div></div><div className="reviews-carousel">{list.map((review) => <article className="review-card" key={`${app.id}-${review.name}`}><div className="review-top"><strong>{review.title}</strong><span>{review.date}</span></div><div className="review-stars">{stars(review.stars)}</div><p>{review.body}</p><footer>{review.name}</footer></article>)}</div></section>; }
function AppRow({ app, onOpen, featured = false, installEntry, onToggleInstall }: { app: StoreApp; onOpen: (app: StoreApp) => void; featured?: boolean; installEntry: InstallEntry; onToggleInstall: (id: string) => void }) { return <article className={`app-row ${featured ? 'featured-row' : ''}`} onClick={() => onOpen(app)}><AppIcon app={app} /><div className="app-row-info"><h3>{app.name}</h3><p>{app.subtitle}</p><div className="rating-line">★ ★ ★ ★ ☆ <span>{app.reviews}</span></div></div><div className="row-action" onClick={(event) => event.stopPropagation()}><ActionButton entry={installEntry} onToggle={() => onToggleInstall(app.id)} />{app.hasInAppPurchases && <small>Встроенные покупки</small>}</div></article>; }
function HeroCard({ app, onOpen, installEntry, onToggleInstall }: { app: StoreApp; onOpen: (app: StoreApp) => void; installEntry: InstallEntry; onToggleInstall: (id: string) => void }) { const bg = appStoreScreenshots[app.id]?.[0]; return <button className={`hero-card ${bg ? 'with-bg' : ''}`} style={bg ? { '--hero-bg': `url(${bg})` } as Record<string, string> : undefined} onClick={() => onOpen(app)}><div><span>Рекомендуем</span><h2>{app.name}</h2><p>{app.description}</p></div><div className="hero-card-footer"><AppIcon app={app} /><div><strong>{app.name}</strong><small>{app.subtitle}</small></div><div onClick={(event) => event.stopPropagation()}><ActionButton entry={installEntry} onToggle={() => onToggleInstall(app.id)} /></div></div></button>; }
function AppDetail({ app, onClose, closing, installEntry, onToggleInstall }: { app: StoreApp; onClose: () => void; closing: boolean; installEntry: InstallEntry; onToggleInstall: (id: string) => void }) { return <section className={`detail-screen ${closing ? 'closing' : ''}`}><div className="detail-nav"><button className="nav-circle" onClick={onClose} aria-label="Назад"><ChevronLeft size={32} /></button><button className="nav-circle share-button" aria-label="Поделиться"><ShareGlyph /></button></div><div className="detail-head"><AppIcon app={app} large /><div><h1>{app.name}</h1><p>{app.subtitle}</p><ActionButton entry={installEntry} onToggle={() => onToggleInstall(app.id)} variant="detail" /></div></div><MetaStrip app={app} />{app.rank && <p className="rank-line">{app.rank}</p>}<AppScreens app={app} /><p className="detail-description">{app.description}</p><Reviews app={app} /><div className="tag-row">{app.tags.map((tag) => <span key={tag}>{tag}</span>)}</div></section>; }
function randomFeaturedIds() { const pool = [...seedApps].sort(() => Math.random() - 0.5); return [pool[0]?.id ?? 'tiktok', pool[1]?.id ?? 'roblox'] as [string, string]; }
export default function App() { const [activeTab, setActiveTab] = useState<Tab>('today'); const [query, setQuery] = useState(''); const [selectedApp, setSelectedApp] = useState<StoreApp | null>(null); const [detailClosing, setDetailClosing] = useState(false); const [installMap, setInstallMap] = useState<Record<string, InstallEntry>>({}); const [featuredIds, setFeaturedIds] = useState<[string, string]>(['tiktok', 'roblox']); const [pullStart, setPullStart] = useState<number | null>(null); const [pullDistance, setPullDistance] = useState(0); const [refreshing, setRefreshing] = useState(false);
  useEffect(() => { const hasLoading = Object.values(installMap).some((entry) => entry.status === 'loading'); if (!hasLoading) return; const timer = window.setInterval(() => setInstallMap((current) => { const next: Record<string, InstallEntry> = { ...current }; Object.entries(current).forEach(([id, entry]) => { if (entry.status === 'loading') next[id] = entry.remaining <= 1 ? { ...entry, status: 'open', remaining: 0 } : { ...entry, remaining: entry.remaining - 1 }; }); return next; }), 1000); return () => window.clearInterval(timer); }, [installMap]);
  function getInstallEntry(appId: string): InstallEntry { return installMap[appId] ?? initialInstall; } function toggleInstall(appId: string) { setInstallMap((current) => { const entry = current[appId] ?? initialInstall; if (entry.status === 'idle') { const duration = downloadDurationFor(appId); return { ...current, [appId]: { status: 'loading', remaining: duration, duration } }; } if (entry.status === 'loading') return { ...current, [appId]: { ...entry, status: 'paused' } }; if (entry.status === 'paused') return { ...current, [appId]: { ...entry, status: 'loading' } }; return current; }); } function openApp(app: StoreApp) { setSelectedApp(app); setDetailClosing(false); } function closeDetail() { setDetailClosing(true); window.setTimeout(() => { setSelectedApp(null); setDetailClosing(false); }, 260); }
  function startRefresh() { if (refreshing || activeTab !== 'today') return; setRefreshing(true); setPullDistance(74); window.setTimeout(() => { setFeaturedIds(randomFeaturedIds()); setRefreshing(false); setPullDistance(0); }, 850); }
  function onTouchStart(event: React.TouchEvent<HTMLElement>) { if (activeTab === 'today' && window.scrollY <= 2 && !refreshing) setPullStart(event.touches[0].clientY); }
  function onTouchMove(event: React.TouchEvent<HTMLElement>) { if (pullStart === null || activeTab !== 'today' || refreshing || window.scrollY > 2) return; const delta = event.touches[0].clientY - pullStart; if (delta > 0) setPullDistance(Math.min(86, delta * 0.72)); }
  function onTouchEnd() { if (pullDistance > 54) startRefresh(); else setPullDistance(0); setPullStart(null); }
  const apps = seedApps.filter((app) => app.kind === 'app'); const games = seedApps.filter((app) => app.kind === 'game'); const searchResults = useMemo(() => seedApps.filter((app) => matchesApp(app, query)), [query]); const visibleList = activeTab === 'games' ? games : activeTab === 'search' ? searchResults : apps; const title = activeTab === 'today' ? 'Сегодня' : activeTab === 'apps' ? 'Приложения' : activeTab === 'games' ? 'Игры' : 'Поиск'; const suggested = query ? searchResults.slice(0, 12) : seedApps.slice(0, 8); const todayHero = seedApps.find((app) => app.id === featuredIds[0]) ?? seedApps[0]; const secondHero = seedApps.find((app) => app.id === featuredIds[1]) ?? seedApps[1]; const appsHero = apps.find((app) => app.id === 'whatsapp') ?? apps[0]; const gamesHero = games.find((app) => app.id === 'brawl-stars') ?? games[0];
  const pullStyle = { '--pull-distance': `${refreshing ? 74 : pullDistance}px`, '--pull-opacity': `${refreshing || pullDistance > 8 ? 1 : 0}` } as CSSProperties;
  return <main className={`phone-shell ${refreshing ? 'refreshing' : ''}`} style={pullStyle} onTouchStart={onTouchStart} onTouchMove={onTouchMove} onTouchEnd={onTouchEnd}><div className="pull-refresh-indicator"><span /></div><header className="ios-header"><h1>{title}</h1><div className="profile-dot">R</div></header>{activeTab === 'search' && <div className="search-panel"><Search size={20} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Игры, приложения и другое" autoFocus />{query && <button onClick={() => setQuery('')}><X size={18} /></button>}</div>}<section className="scroll-area">{activeTab === 'today' && <><HeroCard app={todayHero} onOpen={openApp} installEntry={getInstallEntry(todayHero.id)} onToggleInstall={toggleInstall} /><HeroCard app={secondHero} onOpen={openApp} installEntry={getInstallEntry(secondHero.id)} onToggleInstall={toggleInstall} /><h2 className="section-title">Популярное сегодня</h2>{seedApps.slice(0, 10).map((app) => <AppRow key={app.id} app={app} onOpen={openApp} installEntry={getInstallEntry(app.id)} onToggleInstall={toggleInstall} />)}</>}{activeTab === 'apps' && <><div className="chips">{['AR Apps', 'News', 'Utilities', 'Business'].map((chip) => <span key={chip}>{chip}</span>)}</div>{appsHero && <HeroCard app={appsHero} onOpen={openApp} installEntry={getInstallEntry(appsHero.id)} onToggleInstall={toggleInstall} />}<h2 className="section-title">Must‑Have приложения</h2>{visibleList.slice(0, 30).map((app) => <AppRow key={app.id} app={app} onOpen={openApp} installEntry={getInstallEntry(app.id)} onToggleInstall={toggleInstall} />)}</>}{activeTab === 'games' && <>{gamesHero && <HeroCard app={gamesHero} onOpen={openApp} installEntry={getInstallEntry(gamesHero.id)} onToggleInstall={toggleInstall} />}<h2 className="section-title">Популярные игры</h2>{visibleList.map((app) => <AppRow key={app.id} app={app} onOpen={openApp} installEntry={getInstallEntry(app.id)} onToggleInstall={toggleInstall} />)}</>}{activeTab === 'search' && <><h2 className="section-title">{query ? 'Результаты' : 'Предложенное'}</h2>{suggested.map((app) => <AppRow key={app.id} app={app} onOpen={openApp} featured={app.hasInAppPurchases} installEntry={getInstallEntry(app.id)} onToggleInstall={toggleInstall} />)}{!suggested.length && <p className="empty-text">Ничего не найдено. Напиши мне название приложения, и я добавлю его в RuBox.</p>}</>}</section><nav className="bottom-tabs">{tabs.map(({ id, label, icon: Icon }) => <button key={id} className={activeTab === id ? 'active' : ''} onClick={() => setActiveTab(id)}><Icon size={24} /><span>{label}</span></button>)}</nav>{selectedApp && <AppDetail app={selectedApp} onClose={closeDetail} closing={detailClosing} installEntry={getInstallEntry(selectedApp.id)} onToggleInstall={toggleInstall} />}</main>; }
